# Generated by Django 5.0.3 on 2024-03-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='ContactEmails',
        ),
    ]
