# Generated by Django 5.0.3 on 2024-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_emails_contactemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactemails',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
