# Generated by Django 4.2.9 on 2024-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contactemails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiralModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
