# Generated by Django 4.2.9 on 2024-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_spiralmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiralmodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
