# Generated by Django 4.2.9 on 2024-05-02 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_spiralmodel_audio_alter_spiralmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceBiometrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
            ],
        ),
        migrations.DeleteModel(
            name='SpiralModel',
        ),
        migrations.AddField(
            model_name='contactemails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactemails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
