# Generated by Django 4.2.9 on 2024-05-02 22:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_voicebiometrics_delete_spiralmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicebiometrics',
            name='audio',
            field=models.FileField(default='', upload_to='audio', validators=[api.models.validate_wav_file]),
            preserve_default=False,
        ),
    ]
