# Generated by Django 4.2.9 on 2024-05-04 13:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_voicebiometrics_parkinson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TappyKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='audio', validators=[api.models.validate_wav_file])),
                ('parkinson', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
