# Generated by Django 4.2.9 on 2024-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tappykeyboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tappykeyboard',
            name='file',
            field=models.FileField(upload_to='tappy'),
        ),
    ]
