# Generated by Django 5.0.3 on 2024-05-11 14:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tappykeyboard_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to='audio', validators=[api.models.validate_wav_file])),
                ('parkinson', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
