# Generated by Django 5.0.3 on 2024-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mri',
            name='image',
            field=models.FileField(upload_to='mri'),
        ),
    ]
