# Generated by Django 5.0.3 on 2024-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mri_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mri',
            name='heatmap_image',
            field=models.ImageField(default='', upload_to='heatmap mri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mri',
            name='image',
            field=models.ImageField(upload_to='mri'),
        ),
    ]
