# Generated by Django 5.0.3 on 2024-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mri_heatmap_image_alter_mri_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mri',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmap mri'),
        ),
    ]
